### ISSUE TITLE
Multiple Images

### ISSUE THREAD

**Issue by londonroadhog** [WordPress/classic-editor#102]
I've noticed that if I insert multiple images into the Classic Editor (add Media, then choose multiple images from the Media Library, or upload multiple images and select Insert into Post), I can upload 2 or 3 images successfully, but if I try to insert say 10 images at the same time, the editor seems to just sit there and do nothing. I've contacted my hosting service as I thought it was an issue with their bandwidth, but they are telling me that the issue is with the Classic Editor.

I know I can load the images using the Gallery function, but I didn't want to do it that way. 

Before the Gutenburg update, I could upload and insert as many images as I wanted. Once I uploaded over 30 images into the post without any issues. But since that upgrade I seem to be limited to only a couple of images. This problem could still be a Wordpress issue, rather than the Classic Editor, but thought I'd try to raise it here.

Using Gutenberg, I am forced to use the gallery if I want to insert more than one image at a time, which is making wonder that it could be a Wordpress issue more than the Editor.

**Comment by azaozz** [comment]
Trying with 10 images, all seems to work properly here. 

Are all the images uploaded successfully (can you see them in the media modal or media library)? If yes, what happens when you try to insert them without uploading, i.e. hold down Shift and click on several images, and then click Insert into post?

Closing this here as it seems to be an issue either with uploading or inserting multiple images in TinyMCE. If this continues to happen, can you [post to the support forum](https://wordpress.org/support/plugin/classic-editor/) with the above info.
