### ISSUE TITLE
Remove Block Library styles when Classic Editor is used

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/classic-editor#164]
Hi,

Can you please also dequeue the `wp-block-library` and `wp-block-library-theme` scripts as well, once the Classic Editor is used.

Thanks.

**Comment by kospl** [comment]
Style still added to header when classic editor enabled:

`<link rel='stylesheet' id='wp-block-library-css'  href='https://URLEDITED/wp-includes/css/dist/block-library/style.min.css?ver=5.8.3' type='text/css' media='all' />`

Classic Editor 1.6.2
WordPress 5.8.3

What is best way to remove this? 

This style impacts website performance as it's blocking, and absolutely not needed because classic editor is enabled by default, and users not allowed to switch editors.

**Comment by azaozz** [comment]
Thanks for the comments. 

Thinking this has been discussed many times. As the Classic Editor plugin supports editing in both editors, it would not be wise to remove anything that's needed by the block editor.
