### ISSUE TITLE
Help pls ASAP (cant select categories)

### ISSUE THREAD

**Issue by rstrah** [WordPress/classic-editor#221]
```
tinymce.min.js?ver=49110-20201110:2 Uncaught Error: Node cannot be null or undefined
    at Object.ir [as fromDom] (tinymce.min.js?ver=49110-20201110:2:46730)
    at op (tinymce.min.js?ver=49110-20201110:2:187711)
    at ap (tinymce.min.js?ver=49110-20201110:2:187859)
    at pp.execCommand (tinymce.min.js?ver=49110-20201110:2:189483)
    at tN.execCommand (tinymce.min.js?ver=49110-20201110:2:346040)
    at core.min.js?ver=3.6.0:1:123797
    at h (vendor.min.js?ver=3.6.0:16:41930)
    at y (vendor.min.js?ver=3.6.0:16:42191)
    at m (vendor.min.js?ver=3.6.0:16:42088)
ir @ tinymce.min.js?ver=49110-20201110:2
op @ tinymce.min.js?ver=49110-20201110:2
ap @ tinymce.min.js?ver=49110-20201110:2
execCommand @ tinymce.min.js?ver=49110-20201110:2
execCommand @ tinymce.min.js?ver=49110-20201110:2
(anonymous) @ core.min.js?ver=3.6.0:1
h @ vendor.min.js?ver=3.6.0:16
y @ vendor.min.js?ver=3.6.0:16
m @ vendor.min.js?ver=3.6.0:16
setTimeout
bi @ vendor.min.js?ver=3.6.0:16
v @ vendor.min.js?ver=3.6.0:16
b @ vendor.min.js?ver=3.6.0:16
(anonymous) @ core.min.js?ver=3.6.0:1
requestAnimationFrame
r.contentWindow.onresize @ core.min.js?ver=3.6.0:1
plugin.min.js?ver=49110-20201110:1 Deprecated TinyMCE API call: <target>.onNodeChange.add(..)
```

It is not possible to select categories in the classic news editor. After updating the notes, the categories remain unselected

**Comment by airbesi** [comment]
Same in my website !!

**Comment by azaozz** [comment]
Hi, the TinyMCE error seems unrelated. The problem with saving categories is a core bug that is being fixed in https://core.trac.wordpress.org/ticket/62440.
Also see https://wordpress.org/support/topic/most-used-post-categories-not-saving/.

**Comment by ironprogrammer** [comment]
Hi, @rstrah and @airbesi 👋🏻 Since you shared this report, both [WordPress 6.7.1](https://wordpress.org/news/2024/11/wordpress-6-7-1-maintenance-release/) and [Classic Editor version 1.6.6](https://wordpress.org/plugins/classic-editor/) have been released.

As @azaozz noted above, WP 6.7.1 should resolve the [most used cats issue](https://core.trac.wordpress.org/ticket/62440), and Classic Editor includes a [hotfix related to category selection](https://core.trac.wordpress.org/ticket/62504).

Would you mind updating both and confirming that the category issues are resolved? They aren't related to the plugin specifically, though as a convenience the hotfix was added here. Thanks!

**Comment by azaozz** [comment]
Going to close this as it seems fixed. Feel free to reopen if it still happens when using the latest versions of WordPress and the plugin.
